// app/layout.js or layout.tsx

import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import 'antd/dist/reset.css';
import { ConfigProvider } from "antd";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "E-commerce",
  description: "Generated by create Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.variable}>
        <ConfigProvider>
          <Providers>{children}</Providers>
        </ConfigProvider>
      </body>
    </html>
  );
}
